language: csharp
solution: Trumpf.Coparoo.Web.sln
before_script:
- msbuild /t:Restore Trumpf.Coparoo.Web.sln

install:
- nuget install NUnit.Runners -Version 3.7.0 -OutputDirectory testrunner

script:
- ls -la
- msbuild /p:Configuration=Release Trumpf.Coparoo.Web.sln
- mono ./testrunner/NUnit.Console.3.7.0/tools/nunit3-console.exe ./Trumpf.Coparoo.Web.Tests/bin/Release/net45/Trumpf.Coparoo.Web.Tests.dll